language: php

php:
  - 7.0

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - secure: "d7Wuxpa7KEqgwfLHqTPdfkYvtY2LBfvPcs0jYzqVQe6ZOHOHgvRcaZZKwSwihskMe5F9rea5ifUWxk7qGvL1d83UHecohJMIg7qoI3adv20j677Xr99fIqVkbma3KuIAwEr2bnFZcSyVflBK6wPMLtgvZf3hWxvvuO9V4x8L4GjOqmfuPoXKjFoB4+D0boAZihfxB5/QUEITJStlBMeg8abHfN4sPvXU4RvbAf04IatHYIQh3qGG8+VZh9EqMAnK1I/Sjf9UL6S0UqUagJL7lE842LBeIdqKWz76zyTunDHqIWwvkwqhYX6yGGnkkN0Ttlp4OKvmpj6pLwlI5qmXX/CR7MyBP/r8ud/bK5F3/+YMAY7BgzpDDGeWROt3LN/mC6lcvsLJl48/Dj+g1E+EOPOO8pfxtrvpzO+4awSX1Yt5lTJLx27fWfseX+ZS1FbMCZzj8XZjjRanKpV4FldqwY3QL/Emu+lD5mMn86jp7PWcMECtnYzK+/VdFHI9juBs8ghuW1uVIFltOdy9me4HaLfmO8VLcelvRtNXZx0ak6dBF86M7IiCkQ0VBX1iOtV8Gr0qG70wl/QMwiKGGcIhPA5dq7Q5bHAibmQu9kVxRvBpaH6hPWOFO/JSqlHv0DzEybr4afBUxZmkXKEoHR9+Eu+LmzFAUg3CruIxNSFkBvs="
    - secure: "Rvi4xoUyKbAQHFNqt9wfOSIIKlZRFWEc3LH0TU19ZAPEQdCO6PmL8FzXVo6NbC9aPIncxV8SZFkUJAb0vqwg8AnyasCa8pXgjVk9I5BdE9XVrnHg0ndOItwJGQUrFl/NKKu4kgdbqctNR3FS7hGW4sy+1+LsuWG8GabKG6toA/O9gL49wtgqDPrF6ir2b8WVcMK6TsbGk1u+kJJJZ3Bw4MDjYNw9QrtfC4i7cbCGYDVpsNk0EbXjY8lzp0LLW7NJ1FwCK5oQ40HbcXpH+3rO0Uyslv5s5VI7NbWvuDX3CicrnfFrwYOF7Crcv/AJ9T5lT5Hf9j4NVGRv0XgzhBJ2RlyewrBVTX8XfPO9BsJ6UfejuXUkjVF+M8qnq3u77RSYcjDuGQtF9vPoMMMxA0qP2zI6pT8LMfGVgOLfzd2d2v6c/6oagiYPa1tyKolfANAAUbyjsNEpmtcwKFyK4aVjomJCZoWOYeX5VnFZ3wuEC3FNzLlabtEc9n5oWk19WaU0EVMVSADNsYGXxeY1JifaHdQudlsABVZkXQ9Gt55vxiCTV/XCUFGYv7QiLcwF/JJaYwOzSZYoopIWcFHun/wi9poJlFK9wprs/vDDsFsIuwqPNe7WWf+DnEqDQ8UEJi7GbLeLSUeYpNhSy9m+Egu1u6v1EjHnjTjqwEQNhEV3ZZs="

before_script:
  - composer self-update -q
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
  - if [ -z "$dependencies" ]; then composer install; fi;
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest -n; fi;
  - if [ "$dependencies" = "highest" ]; then composer update -n; fi;
  - composer show -i
  - phpenv config-rm xdebug.ini
  - composer require typo3/cms=^8
  # Restore composer.json
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/.Build/Web
  - touch $PWD/Tests/Functional/.env

script:
  - >
    echo;
    echo "Running functional tests";
    export typo3DatabaseName="typo3";
    export typo3DatabaseHost="localhost";
    export typo3DatabaseUsername="root";
    export typo3DatabasePassword="";
    .Build/bin/phpunit -v -c Tests/Functional/FunctionalTests.xml --group pages
