language: php

php:
  - 7.0

before_install:
  - composer self-update
  - composer --version

before_script:
  # - composer require typo3/minimal=^8
  # Restore composer.json
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/.Build/Web

