language: php

php:
  - 7.0

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  # Restore composer.json
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
  - >
  .Build/bin/phpunit -v -c Tests/Functional/FunctionalTests.xml